/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:95a7893b-fc6d-4e3c-ada7-0035306f89a2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_g6xYTZDsq",
    "aws_user_pools_web_client_id": "7kdv13m6g3vntiglruq30q487j",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://fcvnreaauvar5pulw6mam4r6mu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-t6erg4bbmnbk7lxsbvbxd6jbg4",
    "aws_user_files_s3_bucket": "amplifydemo-image01644-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
