/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:95a7893b-fc6d-4e3c-ada7-0035306f89a2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_g6xYTZDsq",
    "aws_user_pools_web_client_id": "7kdv13m6g3vntiglruq30q487j",
    "oauth": {}
};


export default awsmobile;
